SELECT /*INDEX_COMBINE()E EMP_DEPARTMENT_IX EMP_EMP_ID_PK*/ E.FIRST_NAME, E.LAST_NAME --case9_icomb
FROM EMPLOYEES E, DEPARTMENTS D
WHERE (E.EMPLOYEE_ID = 101 OR E.DEPARTMENT_ID = 10)
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = 1700;
