SELECT /*+LEADING(E) USE_NL(D E)*/ E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE --case_study_7_tuned
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.EMPLOYEE_ID IN (100, 101, 102, 103, 104, 105)
AND E.EMPLOYEE_ID > 0
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID;

