SELECT /*+ LEADING (D2) Case_Study_12 */ E.FIRST_NAME, E.LAST_NAME
FROM   EMPLOYEES E, DEPARTMENTS D, JOBS J, LOCATIONS L, COUNTRIES C
WHERE  E.EMPLOYEE_ID IN (
         SELECT MANAGER_ID
         FROM   DEPARTMENTS D2
         WHERE  DEPARTMENT_ID = 10 )
AND    E.PHONE_NUMBER = '011.44.1344.345268'
AND    E.HIRE_DATE >= TO_DATE('30-JAN-2004 00:00:00','DD-MON-YYYY HH24:MI:SS')
AND    E.HIRE_DATE <= TO_DATE('30-JAN-2006 00:00:00','DD-MON-YYYY HH24:MI:SS')
AND    E.COMMISSION_PCT IN (.25, .15)
AND    E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND    D.LOCATION_ID   = 1700
AND    J.JOB_ID        = E.JOB_ID
AND    J.MIN_SALARY    > 1000
AND    D.LOCATION_ID   = L.LOCATION_ID
AND    L.CITY          = 'Bombay'
AND    C.COUNTRY_ID    = L.COUNTRY_ID
AND    C.REGION_ID     > 3
AND    EXISTS (
         SELECT JOB_ID
         FROM   JOBS J
         WHERE  J.JOB_ID = E.JOB_ID );
