SELECT /*case_study_6*/ E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.EMPLOYEE_ID IN (101, 102, 103, 104, 105)
AND EXISTS (SELECT JOB_ID FROM JOBS J WHERE J.JOB_ID = E.JOB_ID)
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID;
