SELECT /*+ case_study_4*/ E.FIRST_NAME, E.LAST_NAME, E.HIRE_DATE 
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE E.EMPLOYEE_ID = 200
AND D.DEPARTMENT_ID = 10
AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND D.LOCATION_ID = L.LOCATION_ID;
