SELECT E.FIRST_NAME, E.LAST_NAME --case_study_11
FROM   EMPLOYEES E, DEPARTMENTS D
WHERE  E.EMPLOYEE_ID = 101
AND    D.LOCATION_ID IN (
         SELECT LOCATION_ID
         FROM   DEPARTMENTS D1
         WHERE  D1.DEPARTMENT_ID = E.DEPARTMENT_ID )
AND    E.HIRE_DATE > TO_DATE('30-JAN-2004 00:00:00','DD-MON-YYYY HH24:MI:SS')
AND    E.DEPARTMENT_ID = D.DEPARTMENT_ID;
