SELECT E.FIRST_NAME, E.LAST_NAME --case_study_8_equivalent
FROM   EMPLOYEES E, DEPARTMENTS D
WHERE  E.EMPLOYEE_ID = 101
AND    E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND    D.LOCATION_ID = 1700

UNION ALL

SELECT E.FIRST_NAME, E.LAST_NAME
FROM   EMPLOYEES E, DEPARTMENTS D
WHERE  E.DEPARTMENT_ID = 10
AND    E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND    D.LOCATION_ID = 1700;
