SELECT  E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_ID --case_study_14
FROM    EMPLOYEES E, DEPARTMENTS D
WHERE   D.LOCATION_ID = 1800
AND     E.EMPLOYEE_ID = 175
AND     D.DEPARTMENT_ID = E.DEPARTMENT_ID;
